### ISSUE TITLE
SPS30: Could Not Get Auto-Clean Interval

### ISSUE THREAD

**Issue by BismuthOxide7** [paulvha/sps30_on_raspberry#1] opened 2022-07-16 19:37 UTC
I am an absolute beginner using the sps30 with the raspberry pi zero 2w. 

The sensor is connected over i2c with GPIO pins 2 and 3 (i2c1) without external resistors. The 5v power comes straight from the pi using pin 2.

I have been using this program successfully for a few weeks but now I get the error message: `Could not get Auto-Clean Interval` whenever I run the program, no matter what settings I use. 

I have never changed the autoclean interval and I do not know why I get this error.
Any help is appreciated and more details can be provided upon request. 
Thanks.

**Comment by paulvha** [comment] 2022-07-17 08:36
Does the rest of the program / reading work ?

regards,
Paul

**Comment by BismuthOxide7** [comment] 2022-07-17 17:59
No, the error ends the program before it begins taking readings.

**Comment by paulvha** [comment] 2022-07-17 19:15
looks to me a sensor /wiring problem.

What information do you get with -V 2 (debug / versbose) ?

regards,
Paul
________________________________
Van: BismuthOxide7 ***@***.***>
Verzonden: zondag 17 juli 2022 19:59
Aan: paulvha/sps30_on_raspberry ***@***.***>
CC: paulvha ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [paulvha/sps30_on_raspberry] SPS30: Could Not Get Auto-Clean Interval (Issue #1)


No, the error ends the program before it begins taking readings.

**Comment by BismuthOxide7** [comment] 2022-07-18 02:22
It seems that the issue has resolved itself. Running that command gives me the output below.
Running the program with -L 1  as I normally do to test it also works normally now. 
Is there a way to prevent this issue? The way I am setting up the sensor I will not be able to access the rpi to fix the issue as it will be on a stratospheric balloon. (I am running your program automatically using a bash script)
```
I2C Sending:  0x80 0x04
I2C Received: 0x00 0x09 0x3A 0x80 length: 4

I2C Sending:  0xD0 0x33
I2C Received: 0x30 0x39 0x45 0x39 0x46 0x41 0x42 0x42 0x44 0x34 0x32 0x30 0x46 0x46 0x32 0x37 0x00 0x00 length: 18

Serialnumber   09E9FABBD420FF27
I2C Sending:  0xD0 0x02
I2C Received: 0x30 0x30 0x30 0x38 0x30 0x30 0x30 0x30 length: 8

Article code   00080000
I2C Sending:  0xD1 0x00
I2C Received: 0x02 0x03 length: 2

SPS30 Firmware 2.3
I2C Sending:  0x00 0x10 0x03 0x00 0xAC
Starting SPS30 measurement:
I2C Sending:  0x02 0x02
I2C Received: 0x00 0x01 length: 2

I2C Sending:  0x02 0x02
I2C Received: 0x00 0x01 length: 2

I2C Sending:  0x03 0x00
I2C Received: 0x40 0x24 0x79 0xD8 0x40 0x2D 0xED 0x55 0x40 0x2D 0xED 0x55 0x40 0x2D 0xED 0x55 0x41 0x8F 0x90 0xA0 0x41 0xA3 0xB3 0x1C 0x41 0xA4 0x15 0x08 0x41 0xA4 0x20 0xCE 0x41 0xA4 0x2A 0x6E 0x3F 0x02 0xCD 0xC8 length: 40

Sun Jul 17 22:14:54 2022
MASS			      PM1:   2.5699 PM2.5:   2.7176 PM4:   2.7176 PM10:   2.7176
NUM		PM0:  17.9456 PM1:  20.4625 PM2.5:  20.5103 PM4:  20.5160 PM10:  20.5207
I2C Sending:  0xD1 0x00
I2C Received: 0x02 0x03 length: 2

I2C Sending:  0xD2 0x06
I2C Received: 0x00 0x00 0x00 0x00 length: 4

I2C Sending:  0xD2 0x10
Device Status	     No Errors.

^C
Stopping SPS30 monitor
```

**Comment by paulvha** [comment] 2022-07-18 08:03
It is good it is working again, but it is weird. Not knowing the root cause, it is impossible to say how to prevent this. As mentioned earlier, I suspected the wiring. Make sure that it is fixed in a strong way. The push-pins sometimes do not connect well. Better to solder it.  I would let it run for a while under test and if it fails again, check the wiring and 5V. It has to be hardware somewhere.

regards
Paul

**Closed as completed by paulvha** 2022-07-18 08:03 UTC
